import { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { allBlogPosts } from 'contentlayer/generated';
import BlogNotFound from '@/app/components/organisms/errors/BlogNotFound';
import { MDXContent } from '@/app/components/organisms/mdx-content';
import { PostHero } from '@/app/components/organisms/post-hero';
import { createClient } from '@/lib/supabase/server';
import { Locale } from '@/i18n.config';
import { NewsletterSubscribe } from '@/app/components/organisms/newsletter-subscribe';
import { TableOfContents } from '@/app/components/organisms/table-of-contents';
import TailwindGrid from '@/app/components/templates/grid';
import { Breadcrumbs } from '@/app/components/molecules/breadcrumbs';
import { RelatedPosts } from '@/app/components/molecules/related-posts';

interface BlogPostPageProps {
  params: Promise<{
    lang: Locale;
    category: string;
    id: string;
  }>;
}

export async function generateStaticParams() {
  return allBlogPosts.map((post) => {
    const primaryCategory = Array.isArray(post.categories) && post.categories.length > 0
      ? post.categories[0] : 'general';
    const categorySlug = primaryCategory
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[\s\/]+/g, '-');
    return {
      lang: post.locale,
      category: categorySlug,
      id: post.slug,
    };
  });
}

export async function generateMetadata({ params }: BlogPostPageProps): Promise<Metadata> {
  const { lang, id } = await params;
  const post = allBlogPosts.find((p) => p.slug === id && p.locale === lang);

  if (!post) {
    return { title: 'Post Not Found' };
  }

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://alkitu.com';
  const primaryCategory = Array.isArray(post.categories) && post.categories.length > 0
    ? post.categories[0] : 'general';
  const categorySlug = primaryCategory
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[\s\/]+/g, '-');
  const postPath = `/blog/${categorySlug}/${post.slug}`;

  return {
    title: post.title,
    description: post.metaDescription,
    keywords: post.keywords,
    openGraph: {
      title: post.title,
      description: post.metaDescription,
      type: 'article',
      publishedTime: post.date,
      modifiedTime: post.updatedAt || post.date,
      authors: [post.author],
      images: post.image ? [{ url: post.image, width: 1200, height: 630, alt: post.imageAlt }] : [],
      locale: lang === 'es' ? 'es_ES' : 'en_US',
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.metaDescription,
      images: post.image ? [post.image] : [],
    },
    alternates: {
      canonical: `${baseUrl}/${lang}${postPath}`,
    },
  };
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { lang, id } = await params;
  // Find the post by slug and locale
  const post = allBlogPosts.find((p) => p.slug === id && p.locale === lang);

  if (!post) {
    // Return custom Blog 404 instead of global notFound()
    return <BlogNotFound allPosts={allBlogPosts} currentLocale={lang} />;
  }

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://alkitu.com';
  const shareUrl = `${baseUrl}${post.url}`;

  // Get author profile photo if authorUsername exists (direct Supabase fetch)
  let authorPhotoUrl: string | null = null;
  if (post.authorUsername) {
    try {
      const supabase = await createClient();
      const { data: profile } = await supabase
        .from('user_profiles')
        .select('photo_url')
        .eq('username', post.authorUsername)
        .single();

      authorPhotoUrl = profile?.photo_url || null;
    } catch (error) {
      console.error('[BlogPost] Error fetching author photo:', error);
    }
  }

  // Use the Contentlayer-generated structured data
  const jsonLd = post.structuredData;

  return (
    <>
      {/* JSON-LD Schema Markup (Auto-generated by Contentlayer) */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Breadcrumbs */}
      <Breadcrumbs
        locale={lang}
        items={[
          { label: lang === 'es' ? 'Inicio' : 'Home', href: '' },
          { label: 'Blog', href: '/blog' },
          { label: post.title },
        ]}
      />

      {/* Post Hero Section */}
      <PostHero
        title={post.title}
        author={post.author}
        authorUsername={post.authorUsername}
        authorPhotoUrl={authorPhotoUrl}
        date={post.date}
        categories={post.categories}
        tags={post.tags}
        image={post.image}
        imageCredit={post.imageCredit}
        shareUrl={shareUrl}
        locale={lang}
      />

      {/* Post Content Section */}
      <TailwindGrid>
        <article className="col-span-full py-12">
          <div className="max-w-4xl mx-auto px-6">
            {/* Introduction Box */}
            <div className="bg-muted/30 border border-border rounded-lg p-8 mb-12">
              <p className="text-foreground/80 text-base lg:text-lg leading-relaxed italic">
                {post.excerpt}
              </p>
            </div>

            {/* Table of Contents - only show if we have sections */}
            {post.sections && post.sections.length > 0 && (
              <TableOfContents locale={lang} />
            )}

            {/* Main Content - MDX with proper styling */}
            <MDXContent code={post.body.code} />

            {/* Tags Section */}
            {post.tags && post.tags.length > 0 && (
              <div className="mt-12 pt-8 border-t border-border">
                <div className="flex flex-wrap gap-2">
                  {post.tags.map((tag) => {
                    const tagSlug = tag
                      .toLowerCase()
                      .normalize('NFD')
                      .replace(/[\u0300-\u036f]/g, '')
                      .replace(/\s+/g, '-');
                    return (
                      <Link
                        key={tag}
                        href={`/${lang}/blog?tag=${tagSlug}`}
                        className="px-3 py-1 bg-muted text-muted-foreground text-sm rounded-full hover:bg-primary/10 hover:text-primary transition-colors"
                      >
                        #{tag}
                      </Link>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Read Time and Date Info */}
            <div className="mt-8 flex items-center gap-4 text-sm text-muted-foreground">
              <span>{post.readTime}</span>
              {post.updatedAt && post.updatedAt !== post.date && (
                <span>
                  {lang === 'es' ? 'Actualizado:' : 'Updated:'}{' '}
                  {new Date(post.updatedAt).toLocaleDateString(
                    lang === 'es' ? 'es-ES' : 'en-US',
                    { year: 'numeric', month: 'long', day: 'numeric' }
                  )}
                </span>
              )}
            </div>

            {/* Word Count (optional - useful for SEO) */}
            <div className="mt-2 text-xs text-muted-foreground">
              {post.wordCount} {lang === 'es' ? 'palabras' : 'words'}
            </div>

            {/* Related Posts */}
            <RelatedPosts
              locale={lang}
              posts={allBlogPosts
                .filter((p) => p.slug !== post.slug && p.locale === lang)
                .filter((p) =>
                  p.categories.some((c) => post.categories.includes(c)) ||
                  (p.tags && post.tags && p.tags.some((t) => post.tags.includes(t)))
                )
                .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
                .slice(0, 3)
                .map((p) => ({
                  title: p.title,
                  slug: p.slug,
                  url: p.url,
                  image: p.image,
                  excerpt: p.excerpt,
                  readTime: p.readTime,
                }))
              }
            />
          </div>
        </article>
      </TailwindGrid>

      {/* Newsletter Subscription */}
      <NewsletterSubscribe locale={lang} />
    </>
  );
}
