import { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { allBlogPosts } from 'contentlayer/generated';
import BlogNotFound from '@/app/components/organisms/errors/BlogNotFound';
import { MDXContent } from '@/app/components/organisms/mdx-content';
import { PostHero } from '@/app/components/organisms/post-hero';
// ... rest of imports

// ... revalidate and interface ...

// ... generateStaticParams ...

// ... generateMetadata ...

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { lang, id } = await params;
  // Find the post by slug and locale
  const post = allBlogPosts.find((p) => p.slug === id && p.locale === lang);

  if (!post) {
    // Return custom Blog 404 instead of global notFound()
    return <BlogNotFound allPosts={allBlogPosts} currentLocale={lang} />;
  }

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://alkitu.com';
  const shareUrl = `${baseUrl}${post.url}`;

  // Get author profile photo if authorUsername exists (direct Supabase fetch)
  let authorPhotoUrl: string | null = null;
  if (post.authorUsername) {
    try {
      const supabase = await createClient();
      const { data: profile } = await supabase
        .from('user_profiles')
        .select('photo_url')
        .eq('username', post.authorUsername)
        .single();

      authorPhotoUrl = profile?.photo_url || null;
    } catch (error) {
      console.error('[BlogPost] Error fetching author photo:', error);
    }
  }

  // Use the Contentlayer-generated structured data
  const jsonLd = post.structuredData;

  return (
    <>
      {/* JSON-LD Schema Markup (Auto-generated by Contentlayer) */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Post Hero Section */}
      <PostHero
        title={post.title}
        author={post.author}
        authorUsername={post.authorUsername}
        authorPhotoUrl={authorPhotoUrl}
        date={post.date}
        categories={post.categories}
        tags={post.tags}
        image={post.image}
        imageCredit={post.imageCredit}
        shareUrl={shareUrl}
        locale={lang}
      />

      {/* Post Content Section */}
      <TailwindGrid>
        <article className="col-span-full py-12">
          <div className="max-w-4xl mx-auto px-6">
            {/* Introduction Box */}
            <div className="bg-muted/30 border border-border rounded-lg p-8 mb-12">
              <p className="text-foreground/80 text-base lg:text-lg leading-relaxed italic">
                {post.excerpt}
              </p>
            </div>

            {/* Table of Contents - only show if we have sections */}
            {post.sections && post.sections.length > 0 && (
              <TableOfContents locale={lang} />
            )}

            {/* Main Content - MDX with proper styling */}
            <MDXContent code={post.body.code} />

            {/* Tags Section */}
            {post.tags && post.tags.length > 0 && (
              <div className="mt-12 pt-8 border-t border-border">
                <div className="flex flex-wrap gap-2">
                  {post.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-3 py-1 bg-muted text-muted-foreground text-sm rounded-full"
                    >
                      #{tag}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Read Time and Date Info */}
            <div className="mt-8 flex items-center gap-4 text-sm text-muted-foreground">
              <span>{post.readTime}</span>
              {post.updatedAt && post.updatedAt !== post.date && (
                <span>
                  {lang === 'es' ? 'Actualizado:' : 'Updated:'}{' '}
                  {new Date(post.updatedAt).toLocaleDateString(
                    lang === 'es' ? 'es-ES' : 'en-US',
                    { year: 'numeric', month: 'long', day: 'numeric' }
                  )}
                </span>
              )}
            </div>

            {/* Word Count (optional - useful for SEO) */}
            <div className="mt-2 text-xs text-muted-foreground">
              {post.wordCount} {lang === 'es' ? 'palabras' : 'words'}
            </div>
          </div>
        </article>
      </TailwindGrid>

      {/* Newsletter Subscription */}
      <NewsletterSubscribe locale={lang} />
    </>
  );
}
