import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { allBlogPosts } from 'contentlayer/generated';
import { MDXContent } from '@/app/components/organisms/mdx-content';
import { PostHero } from '@/app/components/organisms/post-hero';
import { TableOfContents } from '@/app/components/organisms/table-of-contents';
import { NewsletterSubscribe } from '@/app/components/organisms/newsletter-subscribe';
import TailwindGrid from '@/app/components/templates/grid';
import { Locale } from '@/i18n.config';
import { createClient } from '@/lib/supabase/server';

/**
 * ISR Configuration: Revalidate every hour
 *
 * Enables Incremental Static Regeneration for optimal SEO:
 * - Pages are statically generated at build time
 * - Content updates automatically every hour
 * - Google crawls fast, cached pages
 * - Users always see fresh content
 */
export const revalidate = 3600; // 1 hour in seconds

interface BlogPostPageProps {
  params: Promise<{
    lang: Locale;
    category: string;
    id: string;
  }>;
}

// Generate static params for all blog posts from Contentlayer
export async function generateStaticParams() {
  const paths = allBlogPosts.map((post) => {
    // Extract category slug from first category (primary)
    const primaryCategory = Array.isArray(post.categories) && post.categories.length > 0
      ? post.categories[0]
      : 'general';
    const categorySlug = primaryCategory
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '') // Remove accents
      .replace(/\s+/g, '-');

    return {
      lang: post.locale,
      category: categorySlug,
      id: post.slug,
    };
  });

  return paths;
}

// Generate metadata for SEO from Contentlayer
export async function generateMetadata({ params }: BlogPostPageProps): Promise<Metadata> {
  const { lang, id } = await params;

  // Find the post by slug and locale
  const post = allBlogPosts.find((p) => p.slug === id && p.locale === lang);

  if (!post) {
    return {
      title: 'Post Not Found',
    };
  }

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://alkitu.com';

  return {
    title: post.title,
    description: post.metaDescription,
    keywords: post.keywords.join(', '),
    authors: [{ name: post.author }],
    openGraph: {
      title: post.title,
      description: post.metaDescription,
      url: post.url,
      siteName: 'Alkitu',
      images: [
        {
          url: post.image,
          width: 1200,
          height: 630,
          alt: post.imageAlt,
        },
      ],
      locale: lang === 'es' ? 'es_ES' : 'en_US',
      type: 'article',
      publishedTime: post.date,
      modifiedTime: post.updatedAt || post.date,
      authors: [post.author],
      tags: post.tags,
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.metaDescription,
      images: [post.image],
      creator: '@alkitu',
    },
    alternates: {
      canonical: `${baseUrl}${post.url}`,
      languages: {
        // Find the alternate language version
        ...(allBlogPosts.find((p) => p.slug === post.slug && p.locale === 'es') && {
          es: `${baseUrl}${allBlogPosts.find((p) => p.slug === post.slug && p.locale === 'es')?.url}`,
        }),
        ...(allBlogPosts.find((p) => p.slug === post.slug && p.locale === 'en') && {
          en: `${baseUrl}${allBlogPosts.find((p) => p.slug === post.slug && p.locale === 'en')?.url}`,
        }),
      },
    },
  };
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { lang, id } = await params;

  // Find the post by slug and locale
  const post = allBlogPosts.find((p) => p.slug === id && p.locale === lang);

  if (!post) {
    notFound();
  }

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://alkitu.com';
  const shareUrl = `${baseUrl}${post.url}`;

  // Get author profile photo if authorUsername exists (direct Supabase fetch)
  let authorPhotoUrl: string | null = null;
  if (post.authorUsername) {
    try {
      const supabase = await createClient();
      const { data: profile } = await supabase
        .from('user_profiles')
        .select('photo_url')
        .eq('username', post.authorUsername)
        .single();

      authorPhotoUrl = profile?.photo_url || null;
    } catch (error) {
      console.error('[BlogPost] Error fetching author photo:', error);
    }
  }

  // Use the Contentlayer-generated structured data
  const jsonLd = post.structuredData;

  return (
    <>
      {/* JSON-LD Schema Markup (Auto-generated by Contentlayer) */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Post Hero Section */}
      <PostHero
        title={post.title}
        author={post.author}
        authorUsername={post.authorUsername}
        authorPhotoUrl={authorPhotoUrl}
        date={post.date}
        categories={post.categories}
        tags={post.tags}
        image={post.image}
        imageCredit={post.imageCredit}
        shareUrl={shareUrl}
        locale={lang}
      />

      {/* Post Content Section */}
      <TailwindGrid>
        <article className="col-span-full py-12">
          <div className="max-w-4xl mx-auto px-6">
            {/* Introduction Box */}
            <div className="bg-muted/30 border border-border rounded-lg p-8 mb-12">
              <p className="text-foreground/80 text-base lg:text-lg leading-relaxed italic">
                {post.excerpt}
              </p>
            </div>

            {/* Table of Contents - only show if we have sections */}
            {post.sections && post.sections.length > 0 && (
              <TableOfContents locale={lang} />
            )}

            {/* Main Content - MDX with proper styling */}
            <MDXContent code={post.body.code} />

            {/* Tags Section */}
            {post.tags && post.tags.length > 0 && (
              <div className="mt-12 pt-8 border-t border-border">
                <div className="flex flex-wrap gap-2">
                  {post.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-3 py-1 bg-muted text-muted-foreground text-sm rounded-full"
                    >
                      #{tag}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Read Time and Date Info */}
            <div className="mt-8 flex items-center gap-4 text-sm text-muted-foreground">
              <span>{post.readTime}</span>
              {post.updatedAt && post.updatedAt !== post.date && (
                <span>
                  {lang === 'es' ? 'Actualizado:' : 'Updated:'}{' '}
                  {new Date(post.updatedAt).toLocaleDateString(
                    lang === 'es' ? 'es-ES' : 'en-US',
                    { year: 'numeric', month: 'long', day: 'numeric' }
                  )}
                </span>
              )}
            </div>

            {/* Word Count (optional - useful for SEO) */}
            <div className="mt-2 text-xs text-muted-foreground">
              {post.wordCount} {lang === 'es' ? 'palabras' : 'words'}
            </div>
          </div>
        </article>
      </TailwindGrid>

      {/* Newsletter Subscription */}
      <NewsletterSubscribe locale={lang} />
    </>
  );
}
